"""Convert JSON to JSONB

Revision ID: 20250627_120000
Revises: 20250626_030929
Create Date: 2025-01-27T12:00:00.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250627_120000'
down_revision = '20250626_030929'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Convert JSON columns to JSONB for PostgreSQL (no-op for SQLite)
    if op.get_bind().dialect.name == 'postgresql':
        # User table
        op.alter_column('user', 'permissions',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(),
                   existing_nullable=True)
        op.alter_column('user', 'metadata',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(),
                   existing_nullable=True,
                   new_column_name='user_metadata')
        
        # Device table
        op.alter_column('device', 'device_info',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(),
                   existing_nullable=True)
        
        # NFC Tag table
        op.alter_column('nfc_tag', 'tech_list',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(),
                   existing_nullable=False)
        op.alter_column('nfc_tag', 'read_location',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(),
                   existing_nullable=True)
        op.alter_column('nfc_tag', 'custom_data',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(),
                   existing_nullable=True)
        
        # NFC Record table
        op.alter_column('nfc_record', 'parsed_content',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(),
                   existing_nullable=True,
                   new_column_name='parsed_data')
        
        # Connection table
        op.alter_column('connection', 'connection_data',
                   existing_type=sa.JSON(),
                   type_=postgresql.JSONB(),
                   existing_nullable=True,
                   new_column_name='connection_info')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Convert JSONB columns back to JSON for PostgreSQL (no-op for SQLite)
    if op.get_bind().dialect.name == 'postgresql':
        # Connection table
        op.alter_column('connection', 'connection_info',
                   existing_type=postgresql.JSONB(),
                   type_=sa.JSON(),
                   existing_nullable=True,
                   new_column_name='connection_data')
        
        # NFC Record table
        op.alter_column('nfc_record', 'parsed_data',
                   existing_type=postgresql.JSONB(),
                   type_=sa.JSON(),
                   existing_nullable=True,
                   new_column_name='parsed_content')
        
        # NFC Tag table
        op.alter_column('nfc_tag', 'custom_data',
                   existing_type=postgresql.JSONB(),
                   type_=sa.JSON(),
                   existing_nullable=True)
        op.alter_column('nfc_tag', 'read_location',
                   existing_type=postgresql.JSONB(),
                   type_=sa.JSON(),
                   existing_nullable=True)
        op.alter_column('nfc_tag', 'tech_list',
                   existing_type=postgresql.JSONB(),
                   type_=sa.JSON(),
                   existing_nullable=False)
        
        # Device table
        op.alter_column('device', 'device_info',
                   existing_type=postgresql.JSONB(),
                   type_=sa.JSON(),
                   existing_nullable=True)
        
        # User table
        op.alter_column('user', 'user_metadata',
                   existing_type=postgresql.JSONB(),
                   type_=sa.JSON(),
                   existing_nullable=True,
                   new_column_name='metadata')
        op.alter_column('user', 'permissions',
                   existing_type=postgresql.JSONB(),
                   type_=sa.JSON(),
                   existing_nullable=True)
    
    # ### end Alembic commands ###
